import BenefitsCard from "@/components/cards/benefits-card";
import MultiCarousel from "@/components/multi-carousel/multi-carousel";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Col, Container, Nav, Navbar, Offcanvas, Row } from "react-bootstrap";
import Carousel from "react-bootstrap/Carousel";
import "react-multi-carousel/lib/styles.css";
import HeaderStrip from "../components/header-strip/headerStrip";

export default function Home() {
  const benfitsArr = [
    {
      title: "Health Insurance",
      details:
        "Keeping in mind the heath and happiness of all our employees, a comprehensive healthcare is provided to all the Saasvaapians.",
      imgSrc: "/images/benefits-1.png",
    },
    {
      title: "Career growth",
      details:
        "New opportunities, exposure to different clients, challenging roles; you have all that's needed for a steady growth in career and self-development.",
      imgSrc: "/images/benefits-2.png",
    },
    {
      title: "Career growth",
      details:
        "To better balance professional and personal commitments, we at Saasvaap care for the well-being and work-life balance of our associates and their families.",
      imgSrc: "/images/benefits-3.png",
    },
    {
      title: "Cutting-edge Tech",
      details:
        "You can work on the latest and the cutting-edge technologies in different domains here.",
      imgSrc: "/images/benefits-4.png",
    },
  ];

  return (
    <>
      <Head>
        <title>saasvaap-careers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Cabin:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main>
        <HeaderStrip />
        <header className="main-header">
          <div className="nav-bar-wrap">
            <div className="logo-saasvap">
              <Image
                src="/header-images/saasvaap-logo.png"
                alt="logo"
                width={170}
                height={45}
              />
            </div>

            <Navbar expand="md" className="navbar-main bg-body-primary bg-none">
              <Container className="custom-container">
                <Navbar.Toggle
                  className="custom-toggle-button"
                  aria-controls="basic-navbar-nav"
                />
                <Navbar.Offcanvas
                  id={`offcanvasNavbar-expand-md`}
                  aria-labelledby={`offcanvasNavbarLabel-expand-md`}
                  placement="start"
                  className="d-md-none"
                >
                  <Offcanvas.Header closeButton>
                    <Offcanvas.Title id={`offcanvasNavbarLabel-expand-md`}>
                      <Image
                        src="/header-images/saasvaap-logo.png"
                        alt="logo"
                        width={100}
                        height={30}
                      />
                    </Offcanvas.Title>
                  </Offcanvas.Header>
                  <Offcanvas.Body>
                    <Nav className="justify-content-end flex-grow-1 pe-3">
                      <Nav.Link href="/">HOME</Nav.Link>
                      <Nav.Link href="/">CONTACT US</Nav.Link>
                    </Nav>
                  </Offcanvas.Body>
                </Navbar.Offcanvas>
              </Container>
            </Navbar>

            <div className="nav-wrap-desktop">
              <Link href="/">HOME</Link>
              <Link href="/">CONTACT US</Link>
            </div>
          </div>
        </header>

        <Carousel interval={6000} fade={true}>
          <Carousel.Item>
            <Image
              className="d-block w-100 slider-image"
              src="/images/image1.1b48cc61e5cb3240cb7b.png"
              width={1400}
              height={700}
            />
          </Carousel.Item>
          <Carousel.Item>
            <Image
              src="/images/image3.d1355016ebd236effe5d.jpg"
              className="d-block w-100 slider-image"
              width={1400}
              height={700}
            />
          </Carousel.Item>
          <Carousel.Item>
            <Image
              src="/images/image2.d5d8d526e6804b547eb9.jpg"
              className="d-block w-100 slider-image"
              width={1400}
              height={700}
            />
          </Carousel.Item>
        </Carousel>
        <span className="main-carousel-custom">
          <h2>Inspiring generations to come</h2>
          <div>
            <button className="btn-common">Current Openings</button>
          </div>
        </span>

        <div className="life-saasvaap-wrap">
          <Row className="life-at-section">
            <Col md={6}>
              <h4>Life at Saasvaap</h4>
              <p>
                Saasvaap is a highly competent software service provider that
                builds uniquely tailored and innovative digital solutions and
                products that meet all your business requirements. We work
                passionately with advanced technologies and experts in the field
                to devise the most effective, ideal and compact solutions and
                products for our clients, as we strive to get you closer to your
                bigger goals in business.
              </p>
            </Col>
            <Col md={6}>
              <Image
                src={"/images/life@saasvaap.c3cc4361c231957bbbc5.png"}
                className="img-fluid"
                width={700}
                height={1000}
              />
            </Col>
          </Row>
        </div>

        <div className="benefits-wrap">
          <div className="benifit-headings">
            <h4>Benefits</h4>
            <p>Where Technology and Passion Unites</p>
          </div>
          <Row className="benefit-cards-wrap">
            {benfitsArr.map((item, idx) => (
              <Col key={idx} md={3}>
                <BenefitsCard
                  title={item.title}
                  details={item.details}
                  imgSrc={item.imgSrc}
                />
              </Col>
            ))}
          </Row>
        </div>

        <div className="openings-wrap">
          <div className="openings-headings">
            <h4>Current Openings</h4>
            <p>
              {`Are you looking for an exciting environment to grow as a
              professional? You are at the right place. We might have the ideal
              job you've been looking for.`}
            </p>
          </div>
          <MultiCarousel />
          <div className="current-openings-button-wrapper">
            <button className="btn-common">View More Openings</button>
          </div>
        </div>

        <div className="final-section-wrap">
          <div className="final-section">
            <p className="final-section-text">
              If you still don’t see the opening you were looking for, don’t be
              put off. We’re always looking for talented people. Drop us your
              resume and we’ll let you know when there’s a vacancy.
            </p>
            <Row>
              <Col md={6}>
                <div className="experience">
                  <h4>Got Experience ?</h4>
                  <button className="btn-common">Upload your resume</button>
                </div>
              </Col>
              <Col md={6}>
                <div className="experience">
                  <h4>Are You A Fresher ?</h4>
                  <button className="btn-common">Upload your resume</button>
                </div>
              </Col>
            </Row>
          </div>
        </div>

        <footer className="footer-main">
          <Row className="footer-client-logo-wrap">
            <Col className="col-md-3 col-6 d-flex justify-content-center align-items-center">
              <Image
                src="/images/iso.a6bc5773fd2f5ea080b7.png"
                alt="ISO-certified"
                width={100}
                height={100}
              />
            </Col>
            <Col className="col-md-3 col-6 d-flex justify-content-center align-items-center">
              <Image src="/images/eby.png" alt="ebay" width={100} height={45} />
            </Col>
            <Col className="col-md-3 col-6 d-flex justify-content-center align-items-center">
              <Image
                src="/images/companylogo-3.png"
                alt="paanini"
                width={120}
                height={45}
              />
            </Col>
            <Col className="col-md-3 col-6 d-flex justify-content-center align-items-center">
              <Image
                src="/images/google-logo.png"
                alt="google"
                width={132}
                height={45}
              />
            </Col>
          </Row>

          <Row className="footer-final">
            <Col className="col-md-3 col-6">
              <h4>About Us</h4>
              <p>
                Saasvaap is equipped to develop powerful , lightweight &amp;
                secure solutions with the advantages of digital power for an
                utmost competitive edge in business
              </p>
            </Col>
            <Col className="col-md-3 col-6">
              <h4>Our Services</h4>
              <ul>
                <li>ERP</li>
                <li>Web</li>
                <li>Mobility</li>
                <li>Analytics</li>
                <li>Oodoo Practices</li>
              </ul>
            </Col>
            <Col className="col-md-3 col-5">
              <h4>OUR GROUP OF COMPANIES</h4>
              <img
                className="footer-logo"
                src="/images/saasvaap-footer-logo.png"
                alt="saasvap-footer-logo"
              />
              <p className="Saasvap-India">Saasvaap India</p>
            </Col>
            <Col className="col-md-3 col-7 contact-info">
              <h4>CONTACT INFO</h4>
              <div className="textwidget">
                <Row>
                  <Col className="col-md-4 col-4">Address:</Col>
                  <Col className="col-md-8 col-12">
                    85 Saratoga Avenue,
                    <br />
                    Santa Clara,
                    <br />
                    CA-95051, USA
                  </Col>
                </Row>
                <Row>
                  <Col className="col-md-4 col-4">Phone:</Col>
                  <Col className="col-md-8 col-12">
                    <a href="tel:+14085200753" className="hyperlink-footer">
                      +1 (408) 520- 0753
                    </a>
                    <br />
                    <a href="tel:+14087247219" className="hyperlink-footer">
                      +1 (408) 724- 7219
                    </a>
                  </Col>
                </Row>
                <Row>
                  <Col className="col-md-4 col-4">Mail:</Col>
                  <Col className="col-md-8 col-12">
                    <a
                      href="mailto:enquiries.us@saasvaap.com"
                      className="hyperlink-footer"
                    >
                      enquiries.us@saasvaap.com
                    </a>
                  </Col>
                </Row>
                <Row>
                  <Col className="col-md-4 col-4">Hours:</Col>
                  <Col className="col-md-8 col-12">Mon-Fri</Col>
                </Row>
              </div>
            </Col>
          </Row>
        </footer>
        <div className="copy-right">
          <p>@2022 All Rights Reserved by Saasvaap Inc.</p>
        </div>
      </main>
    </>
  );
}
